/** Declaration file generated by dts-gen */

declare module 'micromodal' {
    export function close(): void;

    export function init(config: any): void;

    export function show(targetModal: any, config: any): void;

    export namespace close {
        const prototype: {
        };

    }

    export namespace init {
        const prototype: {
        };

    }

    export namespace show {
        const prototype: {
        };

    }

}